module: TypeDecoder
author: IBM & Kitura Project Contributors
github_url: https://github.com/Kitura/TypeDecoder

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

