module: TypeDecoder
author: IBM
github_url: https://github.com/IBM-Swift/TypeDecoder

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, TypeDecoder.xcodeproj, -target, TypeDecoder, LIBRARY_SEARCH_PATHS=.build/debug]
